# Generated by Django 3.2 on 2021-04-16 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='API',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('url', models.CharField(max_length=128)),
                ('recent_failure_time', models.DateTimeField(blank=True, null=True)),
                ('failure_strike', models.IntegerField(default=0)),
            ],
        ),
    ]
